svr_list:
  - routeragent
  - gatesvr
  - lobbysvr

gate_listen_tcp: "0.0.0.0:7001"
gate_listen_ws: "0.0.0.0:7002"
lobby_listen_addr: "0.0.0.0:7003"
routeragent_sock_path: "/run/routeragent/ra.sock"
routeragent_listen_addr: "127.0.0.1:7100"
cluster_name: "bidserver"
cluster_env: "dev"
etcd_endpoint_1: "http://tencent.codepeak.cn:2379"
etcd_endpoint_2: "http://tencent.codepeak.cn:2479"
etcd_endpoint_3: "http://tencent.codepeak.cn:2579"
redis_host: "tencent.codepeak.cn"
redis_port_1: 6379
redis_port_2: 6380
redis_port_3: 6381
redis_port_4: 6382
redis_port_5: 6383
redis_port_6: 6384
log_dir: "../log"
REDIS_PWD: "redisCluster123"
