// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.27.0
// source: protos/cluster.proto

package protos

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// RPCType 表示 RPC 调用类型。
type RPCType int32

const (
	RPCType_RPC_TYPE_SYS  RPCType = 0
	RPCType_RPC_TYPE_USER RPCType = 1
)

// Enum value maps for RPCType.
var (
	RPCType_name = map[int32]string{
		0: "RPC_TYPE_SYS",
		1: "RPC_TYPE_USER",
	}
	RPCType_value = map[string]int32{
		"RPC_TYPE_SYS":  0,
		"RPC_TYPE_USER": 1,
	}
)

func (x RPCType) Enum() *RPCType {
	p := new(RPCType)
	*p = x
	return p
}

func (x RPCType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RPCType) Descriptor() protoreflect.EnumDescriptor {
	return file_protos_cluster_proto_enumTypes[0].Descriptor()
}

func (RPCType) Type() protoreflect.EnumType {
	return &file_protos_cluster_proto_enumTypes[0]
}

func (x RPCType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RPCType.Descriptor instead.
func (RPCType) EnumDescriptor() ([]byte, []int) {
	return file_protos_cluster_proto_rawDescGZIP(), []int{0}
}

// MsgType 表示消息类型。
type MsgType int32

const (
	MsgType_MSG_TYPE_REQUEST MsgType = 0
	MsgType_MSG_TYPE_NOTIFY  MsgType = 1
)

// Enum value maps for MsgType.
var (
	MsgType_name = map[int32]string{
		0: "MSG_TYPE_REQUEST",
		1: "MSG_TYPE_NOTIFY",
	}
	MsgType_value = map[string]int32{
		"MSG_TYPE_REQUEST": 0,
		"MSG_TYPE_NOTIFY":  1,
	}
)

func (x MsgType) Enum() *MsgType {
	p := new(MsgType)
	*p = x
	return p
}

func (x MsgType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MsgType) Descriptor() protoreflect.EnumDescriptor {
	return file_protos_cluster_proto_enumTypes[1].Descriptor()
}

func (MsgType) Type() protoreflect.EnumType {
	return &file_protos_cluster_proto_enumTypes[1]
}

func (x MsgType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MsgType.Descriptor instead.
func (MsgType) EnumDescriptor() ([]byte, []int) {
	return file_protos_cluster_proto_rawDescGZIP(), []int{1}
}

// Error 跨服务传输的错误信息。
type Error struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          string                 `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg           string                 `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	Metadata      map[string]string      `protobuf:"bytes,3,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Error) Reset() {
	*x = Error{}
	mi := &file_protos_cluster_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Error) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Error) ProtoMessage() {}

func (x *Error) ProtoReflect() protoreflect.Message {
	mi := &file_protos_cluster_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Error.ProtoReflect.Descriptor instead.
func (*Error) Descriptor() ([]byte, []int) {
	return file_protos_cluster_proto_rawDescGZIP(), []int{0}
}

func (x *Error) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *Error) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *Error) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

// Msg 跨服务传输的消息体。
type Msg struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Route         string                 `protobuf:"bytes,1,opt,name=route,proto3" json:"route,omitempty"`
	Type          MsgType                `protobuf:"varint,2,opt,name=type,proto3,enum=protos.MsgType" json:"type,omitempty"`
	Data          []byte                 `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	Id            uint64                 `protobuf:"varint,4,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Msg) Reset() {
	*x = Msg{}
	mi := &file_protos_cluster_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Msg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Msg) ProtoMessage() {}

func (x *Msg) ProtoReflect() protoreflect.Message {
	mi := &file_protos_cluster_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Msg.ProtoReflect.Descriptor instead.
func (*Msg) Descriptor() ([]byte, []int) {
	return file_protos_cluster_proto_rawDescGZIP(), []int{1}
}

func (x *Msg) GetRoute() string {
	if x != nil {
		return x.Route
	}
	return ""
}

func (x *Msg) GetType() MsgType {
	if x != nil {
		return x.Type
	}
	return MsgType_MSG_TYPE_REQUEST
}

func (x *Msg) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *Msg) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

// Session 跨服务传输的会话数据。
type Session struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Uid           string                 `protobuf:"bytes,2,opt,name=uid,proto3" json:"uid,omitempty"`
	Data          []byte                 `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"` // JSON 序列化的 map[string]interface{}
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Session) Reset() {
	*x = Session{}
	mi := &file_protos_cluster_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Session) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Session) ProtoMessage() {}

func (x *Session) ProtoReflect() protoreflect.Message {
	mi := &file_protos_cluster_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Session.ProtoReflect.Descriptor instead.
func (*Session) Descriptor() ([]byte, []int) {
	return file_protos_cluster_proto_rawDescGZIP(), []int{2}
}

func (x *Session) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Session) GetUid() string {
	if x != nil {
		return x.Uid
	}
	return ""
}

func (x *Session) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

// Request RPC 请求。
type Request struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          RPCType                `protobuf:"varint,1,opt,name=type,proto3,enum=protos.RPCType" json:"type,omitempty"`
	Msg           *Msg                   `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	Metadata      map[string]string      `protobuf:"bytes,3,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	FrontendId    string                 `protobuf:"bytes,4,opt,name=frontend_id,json=frontendId,proto3" json:"frontend_id,omitempty"`
	Session       *Session               `protobuf:"bytes,5,opt,name=session,proto3" json:"session,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Request) Reset() {
	*x = Request{}
	mi := &file_protos_cluster_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Request) ProtoMessage() {}

func (x *Request) ProtoReflect() protoreflect.Message {
	mi := &file_protos_cluster_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Request.ProtoReflect.Descriptor instead.
func (*Request) Descriptor() ([]byte, []int) {
	return file_protos_cluster_proto_rawDescGZIP(), []int{3}
}

func (x *Request) GetType() RPCType {
	if x != nil {
		return x.Type
	}
	return RPCType_RPC_TYPE_SYS
}

func (x *Request) GetMsg() *Msg {
	if x != nil {
		return x.Msg
	}
	return nil
}

func (x *Request) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *Request) GetFrontendId() string {
	if x != nil {
		return x.FrontendId
	}
	return ""
}

func (x *Request) GetSession() *Session {
	if x != nil {
		return x.Session
	}
	return nil
}

// Response RPC 响应。
type Response struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []byte                 `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	Error         *Error                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Response) Reset() {
	*x = Response{}
	mi := &file_protos_cluster_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Response) ProtoMessage() {}

func (x *Response) ProtoReflect() protoreflect.Message {
	mi := &file_protos_cluster_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Response.ProtoReflect.Descriptor instead.
func (*Response) Descriptor() ([]byte, []int) {
	return file_protos_cluster_proto_rawDescGZIP(), []int{4}
}

func (x *Response) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *Response) GetError() *Error {
	if x != nil {
		return x.Error
	}
	return nil
}

// Push 推送消息。
type Push struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Route         string                 `protobuf:"bytes,1,opt,name=route,proto3" json:"route,omitempty"`
	Data          []byte                 `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Push) Reset() {
	*x = Push{}
	mi := &file_protos_cluster_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Push) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Push) ProtoMessage() {}

func (x *Push) ProtoReflect() protoreflect.Message {
	mi := &file_protos_cluster_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Push.ProtoReflect.Descriptor instead.
func (*Push) Descriptor() ([]byte, []int) {
	return file_protos_cluster_proto_rawDescGZIP(), []int{5}
}

func (x *Push) GetRoute() string {
	if x != nil {
		return x.Route
	}
	return ""
}

func (x *Push) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

// KickMsg 踢下线消息。
type KickMsg struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KickMsg) Reset() {
	*x = KickMsg{}
	mi := &file_protos_cluster_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KickMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KickMsg) ProtoMessage() {}

func (x *KickMsg) ProtoReflect() protoreflect.Message {
	mi := &file_protos_cluster_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KickMsg.ProtoReflect.Descriptor instead.
func (*KickMsg) Descriptor() ([]byte, []int) {
	return file_protos_cluster_proto_rawDescGZIP(), []int{6}
}

func (x *KickMsg) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

var File_protos_cluster_proto protoreflect.FileDescriptor

const file_protos_cluster_proto_rawDesc = "" +
	"\n" +
	"\x14protos/cluster.proto\x12\x06protos\"\xa3\x01\n" +
	"\x05Error\x12\x12\n" +
	"\x04code\x18\x01 \x01(\tR\x04code\x12\x10\n" +
	"\x03msg\x18\x02 \x01(\tR\x03msg\x127\n" +
	"\bmetadata\x18\x03 \x03(\v2\x1b.protos.Error.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"d\n" +
	"\x03Msg\x12\x14\n" +
	"\x05route\x18\x01 \x01(\tR\x05route\x12#\n" +
	"\x04type\x18\x02 \x01(\x0e2\x0f.protos.MsgTypeR\x04type\x12\x12\n" +
	"\x04data\x18\x03 \x01(\fR\x04data\x12\x0e\n" +
	"\x02id\x18\x04 \x01(\x04R\x02id\"?\n" +
	"\aSession\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x10\n" +
	"\x03uid\x18\x02 \x01(\tR\x03uid\x12\x12\n" +
	"\x04data\x18\x03 \x01(\fR\x04data\"\x91\x02\n" +
	"\aRequest\x12#\n" +
	"\x04type\x18\x01 \x01(\x0e2\x0f.protos.RPCTypeR\x04type\x12\x1d\n" +
	"\x03msg\x18\x02 \x01(\v2\v.protos.MsgR\x03msg\x129\n" +
	"\bmetadata\x18\x03 \x03(\v2\x1d.protos.Request.MetadataEntryR\bmetadata\x12\x1f\n" +
	"\vfrontend_id\x18\x04 \x01(\tR\n" +
	"frontendId\x12)\n" +
	"\asession\x18\x05 \x01(\v2\x0f.protos.SessionR\asession\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"C\n" +
	"\bResponse\x12\x12\n" +
	"\x04data\x18\x01 \x01(\fR\x04data\x12#\n" +
	"\x05error\x18\x02 \x01(\v2\r.protos.ErrorR\x05error\"0\n" +
	"\x04Push\x12\x14\n" +
	"\x05route\x18\x01 \x01(\tR\x05route\x12\x12\n" +
	"\x04data\x18\x02 \x01(\fR\x04data\"\"\n" +
	"\aKickMsg\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId*.\n" +
	"\aRPCType\x12\x10\n" +
	"\fRPC_TYPE_SYS\x10\x00\x12\x11\n" +
	"\rRPC_TYPE_USER\x10\x01*4\n" +
	"\aMsgType\x12\x14\n" +
	"\x10MSG_TYPE_REQUEST\x10\x00\x12\x13\n" +
	"\x0fMSG_TYPE_NOTIFY\x10\x01B\x1aZ\x18projectbid/server/protosb\x06proto3"

var (
	file_protos_cluster_proto_rawDescOnce sync.Once
	file_protos_cluster_proto_rawDescData []byte
)

func file_protos_cluster_proto_rawDescGZIP() []byte {
	file_protos_cluster_proto_rawDescOnce.Do(func() {
		file_protos_cluster_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_protos_cluster_proto_rawDesc), len(file_protos_cluster_proto_rawDesc)))
	})
	return file_protos_cluster_proto_rawDescData
}

var file_protos_cluster_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_protos_cluster_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_protos_cluster_proto_goTypes = []any{
	(RPCType)(0),     // 0: protos.RPCType
	(MsgType)(0),     // 1: protos.MsgType
	(*Error)(nil),    // 2: protos.Error
	(*Msg)(nil),      // 3: protos.Msg
	(*Session)(nil),  // 4: protos.Session
	(*Request)(nil),  // 5: protos.Request
	(*Response)(nil), // 6: protos.Response
	(*Push)(nil),     // 7: protos.Push
	(*KickMsg)(nil),  // 8: protos.KickMsg
	nil,              // 9: protos.Error.MetadataEntry
	nil,              // 10: protos.Request.MetadataEntry
}
var file_protos_cluster_proto_depIdxs = []int32{
	9,  // 0: protos.Error.metadata:type_name -> protos.Error.MetadataEntry
	1,  // 1: protos.Msg.type:type_name -> protos.MsgType
	0,  // 2: protos.Request.type:type_name -> protos.RPCType
	3,  // 3: protos.Request.msg:type_name -> protos.Msg
	10, // 4: protos.Request.metadata:type_name -> protos.Request.MetadataEntry
	4,  // 5: protos.Request.session:type_name -> protos.Session
	2,  // 6: protos.Response.error:type_name -> protos.Error
	7,  // [7:7] is the sub-list for method output_type
	7,  // [7:7] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_protos_cluster_proto_init() }
func file_protos_cluster_proto_init() {
	if File_protos_cluster_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_protos_cluster_proto_rawDesc), len(file_protos_cluster_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_protos_cluster_proto_goTypes,
		DependencyIndexes: file_protos_cluster_proto_depIdxs,
		EnumInfos:         file_protos_cluster_proto_enumTypes,
		MessageInfos:      file_protos_cluster_proto_msgTypes,
	}.Build()
	File_protos_cluster_proto = out.File
	file_protos_cluster_proto_goTypes = nil
	file_protos_cluster_proto_depIdxs = nil
}
