// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.3
// source: protocol/handler/lobby_handler.proto

package handlerpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	_ "project/protocol/common"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CS_ClaimReward_Req struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CS_ClaimReward_Req) Reset() {
	*x = CS_ClaimReward_Req{}
	mi := &file_protocol_handler_lobby_handler_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CS_ClaimReward_Req) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CS_ClaimReward_Req) ProtoMessage() {}

func (x *CS_ClaimReward_Req) ProtoReflect() protoreflect.Message {
	mi := &file_protocol_handler_lobby_handler_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CS_ClaimReward_Req.ProtoReflect.Descriptor instead.
func (*CS_ClaimReward_Req) Descriptor() ([]byte, []int) {
	return file_protocol_handler_lobby_handler_proto_rawDescGZIP(), []int{0}
}

type SC_ClaimReward_Rsp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SC_ClaimReward_Rsp) Reset() {
	*x = SC_ClaimReward_Rsp{}
	mi := &file_protocol_handler_lobby_handler_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SC_ClaimReward_Rsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SC_ClaimReward_Rsp) ProtoMessage() {}

func (x *SC_ClaimReward_Rsp) ProtoReflect() protoreflect.Message {
	mi := &file_protocol_handler_lobby_handler_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SC_ClaimReward_Rsp.ProtoReflect.Descriptor instead.
func (*SC_ClaimReward_Rsp) Descriptor() ([]byte, []int) {
	return file_protocol_handler_lobby_handler_proto_rawDescGZIP(), []int{1}
}

type CS_SyncPos_Ntf struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CS_SyncPos_Ntf) Reset() {
	*x = CS_SyncPos_Ntf{}
	mi := &file_protocol_handler_lobby_handler_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CS_SyncPos_Ntf) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CS_SyncPos_Ntf) ProtoMessage() {}

func (x *CS_SyncPos_Ntf) ProtoReflect() protoreflect.Message {
	mi := &file_protocol_handler_lobby_handler_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CS_SyncPos_Ntf.ProtoReflect.Descriptor instead.
func (*CS_SyncPos_Ntf) Descriptor() ([]byte, []int) {
	return file_protocol_handler_lobby_handler_proto_rawDescGZIP(), []int{2}
}

var File_protocol_handler_lobby_handler_proto protoreflect.FileDescriptor

const file_protocol_handler_lobby_handler_proto_rawDesc = "" +
	"\n" +
	"$protocol/handler/lobby_handler.proto\x12\x10protocol.handler\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1dprotocol/common/options.proto\"\x1b\n" +
	"\x12CS_ClaimReward_Req:\x05\x98\xb5\x18\x82\x10\"\x1b\n" +
	"\x12SC_ClaimReward_Rsp:\x05\x98\xb5\x18\x83\x10\"\x1b\n" +
	"\x0eCS_SyncPos_Ntf:\t\x98\xb5\x18\x84\x10\xa0\xb5\x18\x012\xb8\x01\n" +
	"\fLobbyHandler\x12Y\n" +
	"\vClaimReward\x12$.protocol.handler.CS_ClaimReward_Req\x1a$.protocol.handler.SC_ClaimReward_Rsp\x12C\n" +
	"\aSyncPos\x12 .protocol.handler.CS_SyncPos_Ntf\x1a\x16.google.protobuf.Empty\x1a\b\x88\xb5\x18\x00\x90\xb5\x18\x02B$Z\"project/protocol/handler;handlerpbb\x06proto3"

var (
	file_protocol_handler_lobby_handler_proto_rawDescOnce sync.Once
	file_protocol_handler_lobby_handler_proto_rawDescData []byte
)

func file_protocol_handler_lobby_handler_proto_rawDescGZIP() []byte {
	file_protocol_handler_lobby_handler_proto_rawDescOnce.Do(func() {
		file_protocol_handler_lobby_handler_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_protocol_handler_lobby_handler_proto_rawDesc), len(file_protocol_handler_lobby_handler_proto_rawDesc)))
	})
	return file_protocol_handler_lobby_handler_proto_rawDescData
}

var file_protocol_handler_lobby_handler_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_protocol_handler_lobby_handler_proto_goTypes = []any{
	(*CS_ClaimReward_Req)(nil), // 0: protocol.handler.CS_ClaimReward_Req
	(*SC_ClaimReward_Rsp)(nil), // 1: protocol.handler.SC_ClaimReward_Rsp
	(*CS_SyncPos_Ntf)(nil),     // 2: protocol.handler.CS_SyncPos_Ntf
	(*emptypb.Empty)(nil),      // 3: google.protobuf.Empty
}
var file_protocol_handler_lobby_handler_proto_depIdxs = []int32{
	0, // 0: protocol.handler.LobbyHandler.ClaimReward:input_type -> protocol.handler.CS_ClaimReward_Req
	2, // 1: protocol.handler.LobbyHandler.SyncPos:input_type -> protocol.handler.CS_SyncPos_Ntf
	1, // 2: protocol.handler.LobbyHandler.ClaimReward:output_type -> protocol.handler.SC_ClaimReward_Rsp
	3, // 3: protocol.handler.LobbyHandler.SyncPos:output_type -> google.protobuf.Empty
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_protocol_handler_lobby_handler_proto_init() }
func file_protocol_handler_lobby_handler_proto_init() {
	if File_protocol_handler_lobby_handler_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_protocol_handler_lobby_handler_proto_rawDesc), len(file_protocol_handler_lobby_handler_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_protocol_handler_lobby_handler_proto_goTypes,
		DependencyIndexes: file_protocol_handler_lobby_handler_proto_depIdxs,
		MessageInfos:      file_protocol_handler_lobby_handler_proto_msgTypes,
	}.Build()
	File_protocol_handler_lobby_handler_proto = out.File
	file_protocol_handler_lobby_handler_proto_goTypes = nil
	file_protocol_handler_lobby_handler_proto_depIdxs = nil
}
