// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.3
// source: protocol/remote/gate_remote.proto

package remotepb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	_ "project/protocol/common"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RPC_SendToClient_Ntf struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RPC_SendToClient_Ntf) Reset() {
	*x = RPC_SendToClient_Ntf{}
	mi := &file_protocol_remote_gate_remote_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RPC_SendToClient_Ntf) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RPC_SendToClient_Ntf) ProtoMessage() {}

func (x *RPC_SendToClient_Ntf) ProtoReflect() protoreflect.Message {
	mi := &file_protocol_remote_gate_remote_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RPC_SendToClient_Ntf.ProtoReflect.Descriptor instead.
func (*RPC_SendToClient_Ntf) Descriptor() ([]byte, []int) {
	return file_protocol_remote_gate_remote_proto_rawDescGZIP(), []int{0}
}

type RPC_BindSession_Ntf struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RPC_BindSession_Ntf) Reset() {
	*x = RPC_BindSession_Ntf{}
	mi := &file_protocol_remote_gate_remote_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RPC_BindSession_Ntf) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RPC_BindSession_Ntf) ProtoMessage() {}

func (x *RPC_BindSession_Ntf) ProtoReflect() protoreflect.Message {
	mi := &file_protocol_remote_gate_remote_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RPC_BindSession_Ntf.ProtoReflect.Descriptor instead.
func (*RPC_BindSession_Ntf) Descriptor() ([]byte, []int) {
	return file_protocol_remote_gate_remote_proto_rawDescGZIP(), []int{1}
}

type RPC_SetBound_Ntf struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RPC_SetBound_Ntf) Reset() {
	*x = RPC_SetBound_Ntf{}
	mi := &file_protocol_remote_gate_remote_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RPC_SetBound_Ntf) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RPC_SetBound_Ntf) ProtoMessage() {}

func (x *RPC_SetBound_Ntf) ProtoReflect() protoreflect.Message {
	mi := &file_protocol_remote_gate_remote_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RPC_SetBound_Ntf.ProtoReflect.Descriptor instead.
func (*RPC_SetBound_Ntf) Descriptor() ([]byte, []int) {
	return file_protocol_remote_gate_remote_proto_rawDescGZIP(), []int{2}
}

var File_protocol_remote_gate_remote_proto protoreflect.FileDescriptor

const file_protocol_remote_gate_remote_proto_rawDesc = "" +
	"\n" +
	"!protocol/remote/gate_remote.proto\x12\x0fprotocol.remote\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1dprotocol/common/options.proto\"\x16\n" +
	"\x14RPC_SendToClient_Ntf\"\x15\n" +
	"\x13RPC_BindSession_Ntf\"\x12\n" +
	"\x10RPC_SetBound_Ntf2\xf9\x01\n" +
	"\n" +
	"GateRemote\x12M\n" +
	"\fSendToClient\x12%.protocol.remote.RPC_SendToClient_Ntf\x1a\x16.google.protobuf.Empty\x12K\n" +
	"\vBindSession\x12$.protocol.remote.RPC_BindSession_Ntf\x1a\x16.google.protobuf.Empty\x12E\n" +
	"\bSetBound\x12!.protocol.remote.RPC_SetBound_Ntf\x1a\x16.google.protobuf.Empty\x1a\b\x88\xb5\x18\x01\x90\xb5\x18\x01B\"Z project/protocol/remote;remotepbb\x06proto3"

var (
	file_protocol_remote_gate_remote_proto_rawDescOnce sync.Once
	file_protocol_remote_gate_remote_proto_rawDescData []byte
)

func file_protocol_remote_gate_remote_proto_rawDescGZIP() []byte {
	file_protocol_remote_gate_remote_proto_rawDescOnce.Do(func() {
		file_protocol_remote_gate_remote_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_protocol_remote_gate_remote_proto_rawDesc), len(file_protocol_remote_gate_remote_proto_rawDesc)))
	})
	return file_protocol_remote_gate_remote_proto_rawDescData
}

var file_protocol_remote_gate_remote_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_protocol_remote_gate_remote_proto_goTypes = []any{
	(*RPC_SendToClient_Ntf)(nil), // 0: protocol.remote.RPC_SendToClient_Ntf
	(*RPC_BindSession_Ntf)(nil),  // 1: protocol.remote.RPC_BindSession_Ntf
	(*RPC_SetBound_Ntf)(nil),     // 2: protocol.remote.RPC_SetBound_Ntf
	(*emptypb.Empty)(nil),        // 3: google.protobuf.Empty
}
var file_protocol_remote_gate_remote_proto_depIdxs = []int32{
	0, // 0: protocol.remote.GateRemote.SendToClient:input_type -> protocol.remote.RPC_SendToClient_Ntf
	1, // 1: protocol.remote.GateRemote.BindSession:input_type -> protocol.remote.RPC_BindSession_Ntf
	2, // 2: protocol.remote.GateRemote.SetBound:input_type -> protocol.remote.RPC_SetBound_Ntf
	3, // 3: protocol.remote.GateRemote.SendToClient:output_type -> google.protobuf.Empty
	3, // 4: protocol.remote.GateRemote.BindSession:output_type -> google.protobuf.Empty
	3, // 5: protocol.remote.GateRemote.SetBound:output_type -> google.protobuf.Empty
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_protocol_remote_gate_remote_proto_init() }
func file_protocol_remote_gate_remote_proto_init() {
	if File_protocol_remote_gate_remote_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_protocol_remote_gate_remote_proto_rawDesc), len(file_protocol_remote_gate_remote_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_protocol_remote_gate_remote_proto_goTypes,
		DependencyIndexes: file_protocol_remote_gate_remote_proto_depIdxs,
		MessageInfos:      file_protocol_remote_gate_remote_proto_msgTypes,
	}.Build()
	File_protocol_remote_gate_remote_proto = out.File
	file_protocol_remote_gate_remote_proto_goTypes = nil
	file_protocol_remote_gate_remote_proto_depIdxs = nil
}
