// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.3
// source: protocol/remote/lobby_remote.proto

package remotepb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	_ "project/protocol/common"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RPC_Test_Req struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RPC_Test_Req) Reset() {
	*x = RPC_Test_Req{}
	mi := &file_protocol_remote_lobby_remote_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RPC_Test_Req) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RPC_Test_Req) ProtoMessage() {}

func (x *RPC_Test_Req) ProtoReflect() protoreflect.Message {
	mi := &file_protocol_remote_lobby_remote_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RPC_Test_Req.ProtoReflect.Descriptor instead.
func (*RPC_Test_Req) Descriptor() ([]byte, []int) {
	return file_protocol_remote_lobby_remote_proto_rawDescGZIP(), []int{0}
}

type RPC_Test_Rsp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RPC_Test_Rsp) Reset() {
	*x = RPC_Test_Rsp{}
	mi := &file_protocol_remote_lobby_remote_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RPC_Test_Rsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RPC_Test_Rsp) ProtoMessage() {}

func (x *RPC_Test_Rsp) ProtoReflect() protoreflect.Message {
	mi := &file_protocol_remote_lobby_remote_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RPC_Test_Rsp.ProtoReflect.Descriptor instead.
func (*RPC_Test_Rsp) Descriptor() ([]byte, []int) {
	return file_protocol_remote_lobby_remote_proto_rawDescGZIP(), []int{1}
}

type RPC_Test_Ntf struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RPC_Test_Ntf) Reset() {
	*x = RPC_Test_Ntf{}
	mi := &file_protocol_remote_lobby_remote_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RPC_Test_Ntf) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RPC_Test_Ntf) ProtoMessage() {}

func (x *RPC_Test_Ntf) ProtoReflect() protoreflect.Message {
	mi := &file_protocol_remote_lobby_remote_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RPC_Test_Ntf.ProtoReflect.Descriptor instead.
func (*RPC_Test_Ntf) Descriptor() ([]byte, []int) {
	return file_protocol_remote_lobby_remote_proto_rawDescGZIP(), []int{2}
}

var File_protocol_remote_lobby_remote_proto protoreflect.FileDescriptor

const file_protocol_remote_lobby_remote_proto_rawDesc = "" +
	"\n" +
	"\"protocol/remote/lobby_remote.proto\x12\x0fprotocol.remote\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1dprotocol/common/options.proto\"\x0e\n" +
	"\fRPC_Test_Req\"\x0e\n" +
	"\fRPC_Test_Rsp\"\x0e\n" +
	"\fRPC_Test_Ntf2\x9f\x01\n" +
	"\vLobbyRemote\x12D\n" +
	"\x04Test\x12\x1d.protocol.remote.RPC_Test_Req\x1a\x1d.protocol.remote.RPC_Test_Rsp\x12@\n" +
	"\aTestNtf\x12\x1d.protocol.remote.RPC_Test_Ntf\x1a\x16.google.protobuf.Empty\x1a\b\x88\xb5\x18\x01\x90\xb5\x18\x02B\"Z project/protocol/remote;remotepbb\x06proto3"

var (
	file_protocol_remote_lobby_remote_proto_rawDescOnce sync.Once
	file_protocol_remote_lobby_remote_proto_rawDescData []byte
)

func file_protocol_remote_lobby_remote_proto_rawDescGZIP() []byte {
	file_protocol_remote_lobby_remote_proto_rawDescOnce.Do(func() {
		file_protocol_remote_lobby_remote_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_protocol_remote_lobby_remote_proto_rawDesc), len(file_protocol_remote_lobby_remote_proto_rawDesc)))
	})
	return file_protocol_remote_lobby_remote_proto_rawDescData
}

var file_protocol_remote_lobby_remote_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_protocol_remote_lobby_remote_proto_goTypes = []any{
	(*RPC_Test_Req)(nil),  // 0: protocol.remote.RPC_Test_Req
	(*RPC_Test_Rsp)(nil),  // 1: protocol.remote.RPC_Test_Rsp
	(*RPC_Test_Ntf)(nil),  // 2: protocol.remote.RPC_Test_Ntf
	(*emptypb.Empty)(nil), // 3: google.protobuf.Empty
}
var file_protocol_remote_lobby_remote_proto_depIdxs = []int32{
	0, // 0: protocol.remote.LobbyRemote.Test:input_type -> protocol.remote.RPC_Test_Req
	2, // 1: protocol.remote.LobbyRemote.TestNtf:input_type -> protocol.remote.RPC_Test_Ntf
	1, // 2: protocol.remote.LobbyRemote.Test:output_type -> protocol.remote.RPC_Test_Rsp
	3, // 3: protocol.remote.LobbyRemote.TestNtf:output_type -> google.protobuf.Empty
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_protocol_remote_lobby_remote_proto_init() }
func file_protocol_remote_lobby_remote_proto_init() {
	if File_protocol_remote_lobby_remote_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_protocol_remote_lobby_remote_proto_rawDesc), len(file_protocol_remote_lobby_remote_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_protocol_remote_lobby_remote_proto_goTypes,
		DependencyIndexes: file_protocol_remote_lobby_remote_proto_depIdxs,
		MessageInfos:      file_protocol_remote_lobby_remote_proto_msgTypes,
	}.Build()
	File_protocol_remote_lobby_remote_proto = out.File
	file_protocol_remote_lobby_remote_proto_goTypes = nil
	file_protocol_remote_lobby_remote_proto_depIdxs = nil
}
