// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.3
// source: protocol/common/errcode.proto

package common

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ErrCode int32

const (
	ErrCode_OK            ErrCode = 0
	ErrCode_ERR_INTERNAL  ErrCode = 1
	ErrCode_ERR_TIMEOUT   ErrCode = 2
	ErrCode_ERR_NO_ROUTE  ErrCode = 3
	ErrCode_ERR_UNAUTHED  ErrCode = 4
	ErrCode_ERR_UNMARSHAL ErrCode = 5
)

// Enum value maps for ErrCode.
var (
	ErrCode_name = map[int32]string{
		0: "OK",
		1: "ERR_INTERNAL",
		2: "ERR_TIMEOUT",
		3: "ERR_NO_ROUTE",
		4: "ERR_UNAUTHED",
		5: "ERR_UNMARSHAL",
	}
	ErrCode_value = map[string]int32{
		"OK":            0,
		"ERR_INTERNAL":  1,
		"ERR_TIMEOUT":   2,
		"ERR_NO_ROUTE":  3,
		"ERR_UNAUTHED":  4,
		"ERR_UNMARSHAL": 5,
	}
)

func (x ErrCode) Enum() *ErrCode {
	p := new(ErrCode)
	*p = x
	return p
}

func (x ErrCode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ErrCode) Descriptor() protoreflect.EnumDescriptor {
	return file_protocol_common_errcode_proto_enumTypes[0].Descriptor()
}

func (ErrCode) Type() protoreflect.EnumType {
	return &file_protocol_common_errcode_proto_enumTypes[0]
}

func (x ErrCode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ErrCode.Descriptor instead.
func (ErrCode) EnumDescriptor() ([]byte, []int) {
	return file_protocol_common_errcode_proto_rawDescGZIP(), []int{0}
}

var File_protocol_common_errcode_proto protoreflect.FileDescriptor

const file_protocol_common_errcode_proto_rawDesc = "" +
	"\n" +
	"\x1dprotocol/common/errcode.proto\x12\x0fprotocol.common*k\n" +
	"\aErrCode\x12\x06\n" +
	"\x02OK\x10\x00\x12\x10\n" +
	"\fERR_INTERNAL\x10\x01\x12\x0f\n" +
	"\vERR_TIMEOUT\x10\x02\x12\x10\n" +
	"\fERR_NO_ROUTE\x10\x03\x12\x10\n" +
	"\fERR_UNAUTHED\x10\x04\x12\x11\n" +
	"\rERR_UNMARSHAL\x10\x05B Z\x1eproject/protocol/common;commonb\x06proto3"

var (
	file_protocol_common_errcode_proto_rawDescOnce sync.Once
	file_protocol_common_errcode_proto_rawDescData []byte
)

func file_protocol_common_errcode_proto_rawDescGZIP() []byte {
	file_protocol_common_errcode_proto_rawDescOnce.Do(func() {
		file_protocol_common_errcode_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_protocol_common_errcode_proto_rawDesc), len(file_protocol_common_errcode_proto_rawDesc)))
	})
	return file_protocol_common_errcode_proto_rawDescData
}

var file_protocol_common_errcode_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_protocol_common_errcode_proto_goTypes = []any{
	(ErrCode)(0), // 0: protocol.common.ErrCode
}
var file_protocol_common_errcode_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_protocol_common_errcode_proto_init() }
func file_protocol_common_errcode_proto_init() {
	if File_protocol_common_errcode_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_protocol_common_errcode_proto_rawDesc), len(file_protocol_common_errcode_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_protocol_common_errcode_proto_goTypes,
		DependencyIndexes: file_protocol_common_errcode_proto_depIdxs,
		EnumInfos:         file_protocol_common_errcode_proto_enumTypes,
	}.Build()
	File_protocol_common_errcode_proto = out.File
	file_protocol_common_errcode_proto_goTypes = nil
	file_protocol_common_errcode_proto_depIdxs = nil
}
