// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.3
// source: protocol/common/node.proto

package common

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ServerType int32

const (
	ServerType_ST_UNKNOWN     ServerType = 0
	ServerType_ST_GATESVR     ServerType = 1
	ServerType_ST_LOBBYSVR    ServerType = 2
	ServerType_ST_ROOMSVR     ServerType = 3
	ServerType_ST_MATCHSVR    ServerType = 4
	ServerType_ST_ONLINESVR   ServerType = 5
	ServerType_ST_ROUTERAGENT ServerType = 6
)

// Enum value maps for ServerType.
var (
	ServerType_name = map[int32]string{
		0: "ST_UNKNOWN",
		1: "ST_GATESVR",
		2: "ST_LOBBYSVR",
		3: "ST_ROOMSVR",
		4: "ST_MATCHSVR",
		5: "ST_ONLINESVR",
		6: "ST_ROUTERAGENT",
	}
	ServerType_value = map[string]int32{
		"ST_UNKNOWN":     0,
		"ST_GATESVR":     1,
		"ST_LOBBYSVR":    2,
		"ST_ROOMSVR":     3,
		"ST_MATCHSVR":    4,
		"ST_ONLINESVR":   5,
		"ST_ROUTERAGENT": 6,
	}
)

func (x ServerType) Enum() *ServerType {
	p := new(ServerType)
	*p = x
	return p
}

func (x ServerType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ServerType) Descriptor() protoreflect.EnumDescriptor {
	return file_protocol_common_node_proto_enumTypes[0].Descriptor()
}

func (ServerType) Type() protoreflect.EnumType {
	return &file_protocol_common_node_proto_enumTypes[0]
}

func (x ServerType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ServerType.Descriptor instead.
func (ServerType) EnumDescriptor() ([]byte, []int) {
	return file_protocol_common_node_proto_rawDescGZIP(), []int{0}
}

var File_protocol_common_node_proto protoreflect.FileDescriptor

const file_protocol_common_node_proto_rawDesc = "" +
	"\n" +
	"\x1aprotocol/common/node.proto\x12\x0fprotocol.common*\x84\x01\n" +
	"\n" +
	"ServerType\x12\x0e\n" +
	"\n" +
	"ST_UNKNOWN\x10\x00\x12\x0e\n" +
	"\n" +
	"ST_GATESVR\x10\x01\x12\x0f\n" +
	"\vST_LOBBYSVR\x10\x02\x12\x0e\n" +
	"\n" +
	"ST_ROOMSVR\x10\x03\x12\x0f\n" +
	"\vST_MATCHSVR\x10\x04\x12\x10\n" +
	"\fST_ONLINESVR\x10\x05\x12\x12\n" +
	"\x0eST_ROUTERAGENT\x10\x06B Z\x1eproject/protocol/common;commonb\x06proto3"

var (
	file_protocol_common_node_proto_rawDescOnce sync.Once
	file_protocol_common_node_proto_rawDescData []byte
)

func file_protocol_common_node_proto_rawDescGZIP() []byte {
	file_protocol_common_node_proto_rawDescOnce.Do(func() {
		file_protocol_common_node_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_protocol_common_node_proto_rawDesc), len(file_protocol_common_node_proto_rawDesc)))
	})
	return file_protocol_common_node_proto_rawDescData
}

var file_protocol_common_node_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_protocol_common_node_proto_goTypes = []any{
	(ServerType)(0), // 0: protocol.common.ServerType
}
var file_protocol_common_node_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_protocol_common_node_proto_init() }
func file_protocol_common_node_proto_init() {
	if File_protocol_common_node_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_protocol_common_node_proto_rawDesc), len(file_protocol_common_node_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_protocol_common_node_proto_goTypes,
		DependencyIndexes: file_protocol_common_node_proto_depIdxs,
		EnumInfos:         file_protocol_common_node_proto_enumTypes,
	}.Build()
	File_protocol_common_node_proto = out.File
	file_protocol_common_node_proto_goTypes = nil
	file_protocol_common_node_proto_depIdxs = nil
}
