// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.1
// source: protocal/cluster.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// NodeInfo etcd value，节点的完整信息
type NodeInfo struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	NodeId         string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`                           // NodeID 点分格式，如 "1.2.1"
	ServerTypeName string                 `protobuf:"bytes,2,opt,name=server_type_name,json=serverTypeName,proto3" json:"server_type_name,omitempty"` // 服务类型名称，如 "lobbysvr"
	Subject        string                 `protobuf:"bytes,3,opt,name=subject,proto3" json:"subject,omitempty"`                                       // NATS subject，等于 node_id
	Addr           string                 `protobuf:"bytes,4,opt,name=addr,proto3" json:"addr,omitempty"`                                             // 对外地址
	StartTime      int64                  `protobuf:"varint,5,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`                 // Unix 时间戳
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *NodeInfo) Reset() {
	*x = NodeInfo{}
	mi := &file_protocal_cluster_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodeInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeInfo) ProtoMessage() {}

func (x *NodeInfo) ProtoReflect() protoreflect.Message {
	mi := &file_protocal_cluster_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeInfo.ProtoReflect.Descriptor instead.
func (*NodeInfo) Descriptor() ([]byte, []int) {
	return file_protocal_cluster_proto_rawDescGZIP(), []int{0}
}

func (x *NodeInfo) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *NodeInfo) GetServerTypeName() string {
	if x != nil {
		return x.ServerTypeName
	}
	return ""
}

func (x *NodeInfo) GetSubject() string {
	if x != nil {
		return x.Subject
	}
	return ""
}

func (x *NodeInfo) GetAddr() string {
	if x != nil {
		return x.Addr
	}
	return ""
}

func (x *NodeInfo) GetStartTime() int64 {
	if x != nil {
		return x.StartTime
	}
	return 0
}

// ClusterSession 集群间传递的轻量 session 数据（纯数据，不含连接状态）
type ClusterSession struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Uid           int64                  `protobuf:"varint,2,opt,name=uid,proto3" json:"uid,omitempty"`
	Ip            string                 `protobuf:"bytes,3,opt,name=ip,proto3" json:"ip,omitempty"`
	FrontendId    string                 `protobuf:"bytes,4,opt,name=frontend_id,json=frontendId,proto3" json:"frontend_id,omitempty"`
	Data          []byte                 `protobuf:"bytes,5,opt,name=data,proto3" json:"data,omitempty"`                             // session.data 序列化后的字节
	ClientMid     uint32                 `protobuf:"varint,6,opt,name=client_mid,json=clientMid,proto3" json:"client_mid,omitempty"` // 客户端原始 MID，0 表示 OneWay（gate 转发时填入）
	MsgType       uint32                 `protobuf:"varint,7,opt,name=msg_type,json=msgType,proto3" json:"msg_type,omitempty"`       // 对应 message.Type：1=Request, 3=OneWay
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClusterSession) Reset() {
	*x = ClusterSession{}
	mi := &file_protocal_cluster_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClusterSession) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClusterSession) ProtoMessage() {}

func (x *ClusterSession) ProtoReflect() protoreflect.Message {
	mi := &file_protocal_cluster_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClusterSession.ProtoReflect.Descriptor instead.
func (*ClusterSession) Descriptor() ([]byte, []int) {
	return file_protocal_cluster_proto_rawDescGZIP(), []int{1}
}

func (x *ClusterSession) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ClusterSession) GetUid() int64 {
	if x != nil {
		return x.Uid
	}
	return 0
}

func (x *ClusterSession) GetIp() string {
	if x != nil {
		return x.Ip
	}
	return ""
}

func (x *ClusterSession) GetFrontendId() string {
	if x != nil {
		return x.FrontendId
	}
	return ""
}

func (x *ClusterSession) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *ClusterSession) GetClientMid() uint32 {
	if x != nil {
		return x.ClientMid
	}
	return 0
}

func (x *ClusterSession) GetMsgType() uint32 {
	if x != nil {
		return x.MsgType
	}
	return 0
}

// ClusterMessage 集群内部 RPC 请求封装
type ClusterMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	From          string                 `protobuf:"bytes,1,opt,name=from,proto3" json:"from,omitempty"`                      // 发送方 NodeID.Subject()
	Route         string                 `protobuf:"bytes,2,opt,name=route,proto3" json:"route,omitempty"`                    // 目标 handler route（由 msg_id 查路由表得到）
	Data          []byte                 `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`                      // 业务 payload（protobuf 序列化）
	Session       *ClusterSession        `protobuf:"bytes,4,opt,name=session,proto3" json:"session,omitempty"`                // 可选，调用方 session
	TraceId       string                 `protobuf:"bytes,5,opt,name=trace_id,json=traceId,proto3" json:"trace_id,omitempty"` // 链路追踪 ID
	Deadline      int64                  `protobuf:"varint,6,opt,name=deadline,proto3" json:"deadline,omitempty"`             // 超时截止时间，Unix 纳秒；0 表示不限
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClusterMessage) Reset() {
	*x = ClusterMessage{}
	mi := &file_protocal_cluster_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClusterMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClusterMessage) ProtoMessage() {}

func (x *ClusterMessage) ProtoReflect() protoreflect.Message {
	mi := &file_protocal_cluster_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClusterMessage.ProtoReflect.Descriptor instead.
func (*ClusterMessage) Descriptor() ([]byte, []int) {
	return file_protocal_cluster_proto_rawDescGZIP(), []int{2}
}

func (x *ClusterMessage) GetFrom() string {
	if x != nil {
		return x.From
	}
	return ""
}

func (x *ClusterMessage) GetRoute() string {
	if x != nil {
		return x.Route
	}
	return ""
}

func (x *ClusterMessage) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *ClusterMessage) GetSession() *ClusterSession {
	if x != nil {
		return x.Session
	}
	return nil
}

func (x *ClusterMessage) GetTraceId() string {
	if x != nil {
		return x.TraceId
	}
	return ""
}

func (x *ClusterMessage) GetDeadline() int64 {
	if x != nil {
		return x.Deadline
	}
	return 0
}

// ClusterResponse 集群内部 RPC 响应封装
type ClusterResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []byte                 `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`                   // 返回数据（protobuf 序列化）
	ErrMsg        string                 `protobuf:"bytes,2,opt,name=err_msg,json=errMsg,proto3" json:"err_msg,omitempty"` // 错误信息，空表示成功
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClusterResponse) Reset() {
	*x = ClusterResponse{}
	mi := &file_protocal_cluster_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClusterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClusterResponse) ProtoMessage() {}

func (x *ClusterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protocal_cluster_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClusterResponse.ProtoReflect.Descriptor instead.
func (*ClusterResponse) Descriptor() ([]byte, []int) {
	return file_protocal_cluster_proto_rawDescGZIP(), []int{3}
}

func (x *ClusterResponse) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *ClusterResponse) GetErrMsg() string {
	if x != nil {
		return x.ErrMsg
	}
	return ""
}

var File_protocal_cluster_proto protoreflect.FileDescriptor

const file_protocal_cluster_proto_rawDesc = "" +
	"\n" +
	"\x16protocal/cluster.proto\x12\acluster\"\x9a\x01\n" +
	"\bNodeInfo\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12(\n" +
	"\x10server_type_name\x18\x02 \x01(\tR\x0eserverTypeName\x12\x18\n" +
	"\asubject\x18\x03 \x01(\tR\asubject\x12\x12\n" +
	"\x04addr\x18\x04 \x01(\tR\x04addr\x12\x1d\n" +
	"\n" +
	"start_time\x18\x05 \x01(\x03R\tstartTime\"\xb1\x01\n" +
	"\x0eClusterSession\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x10\n" +
	"\x03uid\x18\x02 \x01(\x03R\x03uid\x12\x0e\n" +
	"\x02ip\x18\x03 \x01(\tR\x02ip\x12\x1f\n" +
	"\vfrontend_id\x18\x04 \x01(\tR\n" +
	"frontendId\x12\x12\n" +
	"\x04data\x18\x05 \x01(\fR\x04data\x12\x1d\n" +
	"\n" +
	"client_mid\x18\x06 \x01(\rR\tclientMid\x12\x19\n" +
	"\bmsg_type\x18\a \x01(\rR\amsgType\"\xb8\x01\n" +
	"\x0eClusterMessage\x12\x12\n" +
	"\x04from\x18\x01 \x01(\tR\x04from\x12\x14\n" +
	"\x05route\x18\x02 \x01(\tR\x05route\x12\x12\n" +
	"\x04data\x18\x03 \x01(\fR\x04data\x121\n" +
	"\asession\x18\x04 \x01(\v2\x17.cluster.ClusterSessionR\asession\x12\x19\n" +
	"\btrace_id\x18\x05 \x01(\tR\atraceId\x12\x1a\n" +
	"\bdeadline\x18\x06 \x01(\x03R\bdeadline\">\n" +
	"\x0fClusterResponse\x12\x12\n" +
	"\x04data\x18\x01 \x01(\fR\x04data\x12\x17\n" +
	"\aerr_msg\x18\x02 \x01(\tR\x06errMsgB\"Z project/src/framework/cluster/pbb\x06proto3"

var (
	file_protocal_cluster_proto_rawDescOnce sync.Once
	file_protocal_cluster_proto_rawDescData []byte
)

func file_protocal_cluster_proto_rawDescGZIP() []byte {
	file_protocal_cluster_proto_rawDescOnce.Do(func() {
		file_protocal_cluster_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_protocal_cluster_proto_rawDesc), len(file_protocal_cluster_proto_rawDesc)))
	})
	return file_protocal_cluster_proto_rawDescData
}

var file_protocal_cluster_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_protocal_cluster_proto_goTypes = []any{
	(*NodeInfo)(nil),        // 0: cluster.NodeInfo
	(*ClusterSession)(nil),  // 1: cluster.ClusterSession
	(*ClusterMessage)(nil),  // 2: cluster.ClusterMessage
	(*ClusterResponse)(nil), // 3: cluster.ClusterResponse
}
var file_protocal_cluster_proto_depIdxs = []int32{
	1, // 0: cluster.ClusterMessage.session:type_name -> cluster.ClusterSession
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_protocal_cluster_proto_init() }
func file_protocal_cluster_proto_init() {
	if File_protocal_cluster_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_protocal_cluster_proto_rawDesc), len(file_protocal_cluster_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_protocal_cluster_proto_goTypes,
		DependencyIndexes: file_protocal_cluster_proto_depIdxs,
		MessageInfos:      file_protocal_cluster_proto_msgTypes,
	}.Build()
	File_protocal_cluster_proto = out.File
	file_protocal_cluster_proto_goTypes = nil
	file_protocal_cluster_proto_depIdxs = nil
}
