// gen_routes 扫描 protocal/ 目录下所有 .proto 文件，
// 提取 msg_id、server_type、handler_method option，生成路由映射表。
//
// 用法：go run ./tools/gen_routes
package main

import (
	"bufio"
	"fmt"
	"os"
	"path/filepath"
	"regexp"
	"sort"
	"strconv"
	"strings"
)

type msgInfo struct {
	name          string
	msgID         uint32
	serverType    string
	handlerMethod string
}

var (
	msgBlockRe      = regexp.MustCompile(`(?s)message\s+(\w+)\s*\{([^}]*)\}`)
	msgIDRe         = regexp.MustCompile(`\(options\.msg_id\)\s*=\s*(\d+)`)
	serverTypeRe    = regexp.MustCompile(`\(options\.server_type\)\s*=\s*"([^"]+)"`)
	handlerMethodRe = regexp.MustCompile(`\(options\.handler_method\)\s*=\s*"([^"]+)"`)
)

func main() {
	protoDir := "protocal"
	outDir := "protocal/gen/routes"

	var msgs []msgInfo

	err := filepath.WalkDir(protoDir, func(path string, d os.DirEntry, err error) error {
		if err != nil || d.IsDir() || !strings.HasSuffix(path, ".proto") {
			return err
		}
		// 跳过 options.proto 和 cluster.proto（系统 proto，不含业务消息）
		base := filepath.Base(path)
		if base == "options.proto" || base == "cluster.proto" {
			return nil
		}
		parsed, parseErr := parseProto(path)
		if parseErr != nil {
			fmt.Fprintf(os.Stderr, "parse %s failed: %v\n", path, parseErr)
			return nil
		}
		msgs = append(msgs, parsed...)
		return nil
	})
	if err != nil {
		fmt.Fprintf(os.Stderr, "walk failed: %v\n", err)
		os.Exit(1)
	}

	// 按 msgID 排序，生成稳定输出
	sort.Slice(msgs, func(i, j int) bool { return msgs[i].msgID < msgs[j].msgID })

	if err := os.MkdirAll(outDir, 0755); err != nil {
		fmt.Fprintf(os.Stderr, "mkdir failed: %v\n", err)
		os.Exit(1)
	}

	if err := generateRouteFile(outDir, msgs); err != nil {
		fmt.Fprintf(os.Stderr, "generate failed: %v\n", err)
		os.Exit(1)
	}

	fmt.Printf("generated %d message routes → %s/routes.go\n", len(msgs), outDir)
}

func parseProto(path string) ([]msgInfo, error) {
	f, err := os.Open(path)
	if err != nil {
		return nil, err
	}
	defer f.Close()

	var sb strings.Builder
	scanner := bufio.NewScanner(f)
	for scanner.Scan() {
		line := scanner.Text()
		// 去掉行注释，避免干扰正则
		if idx := strings.Index(line, "//"); idx >= 0 {
			line = line[:idx]
		}
		sb.WriteString(line + "\n")
	}
	content := sb.String()

	var result []msgInfo
	for _, m := range msgBlockRe.FindAllStringSubmatch(content, -1) {
		name := m[1]
		body := m[2]

		idMatch := msgIDRe.FindStringSubmatch(body)
		if idMatch == nil {
			continue
		}
		id64, _ := strconv.ParseUint(idMatch[1], 10, 32)
		msgID := uint32(id64)

		var serverType, handlerMethod string
		if st := serverTypeRe.FindStringSubmatch(body); st != nil {
			serverType = st[1]
		}
		if hm := handlerMethodRe.FindStringSubmatch(body); hm != nil {
			handlerMethod = hm[1]
		} else if serverType != "" {
			// 未指定 handler_method 时，按消息名自动推导
			// CS_ClaimReward_Req → 去掉前缀 CS_，去掉后缀 _Req/_OneWay，转小写
			handlerMethod = inferHandlerMethod(name, serverType)
		}

		result = append(result, msgInfo{
			name:          name,
			msgID:         msgID,
			serverType:    serverType,
			handlerMethod: handlerMethod,
		})
	}
	return result, nil
}

// inferHandlerMethod 从消息名推导 handler 方法名
// CS_ClaimReward_Req → "HandlerTypeName.claimreward"（需要 server_type 推导类型名）
func inferHandlerMethod(msgName, serverType string) string {
	// 去掉 CS_/SC_/RPC_ 前缀
	name := msgName
	for _, prefix := range []string{"CS_", "SC_", "RPC_"} {
		name = strings.TrimPrefix(name, prefix)
	}
	// 去掉 _Req/_Rsp/_OneWay 后缀
	for _, suffix := range []string{"_Req", "_Rsp", "_OneWay"} {
		name = strings.TrimSuffix(name, suffix)
	}
	// 推导类型名：worldsvr → WorldHandler
	typeName := strings.Title(strings.TrimSuffix(serverType, "svr")) + "Handler"
	return typeName + "." + strings.ToLower(name)
}

func generateRouteFile(outDir string, msgs []msgInfo) error {
	var sb strings.Builder
	sb.WriteString("// Code generated by tools/gen_routes. DO NOT EDIT.\n")
	sb.WriteString("// Run: go run ./tools/gen_routes\n\n")
	sb.WriteString("package routes\n\n")

	// MsgRouteTable：有 handlerMethod 且无 serverType（本地处理）
	// 或有 handlerMethod 且有 serverType（backend 上本地处理）
	sb.WriteString("// MsgRouteTable msgID → handler route，服务器本地处理用\n")
	sb.WriteString("var MsgRouteTable = map[uint32]string{\n")
	for _, m := range msgs {
		if m.handlerMethod != "" {
			sb.WriteString(fmt.Sprintf("\t%d: %q, // %s\n", m.msgID, m.handlerMethod, m.name))
		}
	}
	sb.WriteString("}\n\n")

	// ForwardTable：有 serverType 的消息（gate 需要转发）
	sb.WriteString("// ForwardTable msgID → 目标 serverType，gate 转发用\n")
	sb.WriteString("var ForwardTable = map[uint32]string{\n")
	for _, m := range msgs {
		if m.serverType != "" {
			sb.WriteString(fmt.Sprintf("\t%d: %q, // %s\n", m.msgID, m.serverType, m.name))
		}
	}
	sb.WriteString("}\n\n")

	// RespMsgIDTable：推导请求→响应的 msgID 映射（相邻奇偶数约定）
	// 约定：请求 msgID 为奇数，响应为 请求+1
	// 也可以通过 proto option 显式指定，此处用简单约定
	sb.WriteString("// RespMsgIDTable 请求 msgID → 响应 msgID\n")
	sb.WriteString("var RespMsgIDTable = map[uint32]uint32{\n")
	// 构建 msgID set
	idSet := make(map[uint32]bool)
	for _, m := range msgs {
		idSet[m.msgID] = true
	}
	for _, m := range msgs {
		if m.serverType != "" && idSet[m.msgID+1] {
			sb.WriteString(fmt.Sprintf("\t%d: %d, // %s\n", m.msgID, m.msgID+1, m.name))
		}
	}
	sb.WriteString("}\n\n")

	// Config 辅助函数，供 app.WithRoutes 一行调用
	sb.WriteString("// Config 返回所有路由表，供 app.WithRoutes(routes.Config()) 使用\n")
	sb.WriteString("func Config() (map[uint32]string, map[uint32]string, map[uint32]uint32) {\n")
	sb.WriteString("\treturn MsgRouteTable, ForwardTable, RespMsgIDTable\n")
	sb.WriteString("}\n")

	outPath := filepath.Join(outDir, "routes.go")
	return os.WriteFile(outPath, []byte(sb.String()), 0644)
}
