// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.3
// source: protocol/handler/match_handler.proto

package handlerpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	_ "project/protocol/common"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CS_StartMatch_Req struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CS_StartMatch_Req) Reset() {
	*x = CS_StartMatch_Req{}
	mi := &file_protocol_handler_match_handler_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CS_StartMatch_Req) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CS_StartMatch_Req) ProtoMessage() {}

func (x *CS_StartMatch_Req) ProtoReflect() protoreflect.Message {
	mi := &file_protocol_handler_match_handler_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CS_StartMatch_Req.ProtoReflect.Descriptor instead.
func (*CS_StartMatch_Req) Descriptor() ([]byte, []int) {
	return file_protocol_handler_match_handler_proto_rawDescGZIP(), []int{0}
}

type SC_StartMatch_Rsp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SC_StartMatch_Rsp) Reset() {
	*x = SC_StartMatch_Rsp{}
	mi := &file_protocol_handler_match_handler_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SC_StartMatch_Rsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SC_StartMatch_Rsp) ProtoMessage() {}

func (x *SC_StartMatch_Rsp) ProtoReflect() protoreflect.Message {
	mi := &file_protocol_handler_match_handler_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SC_StartMatch_Rsp.ProtoReflect.Descriptor instead.
func (*SC_StartMatch_Rsp) Descriptor() ([]byte, []int) {
	return file_protocol_handler_match_handler_proto_rawDescGZIP(), []int{1}
}

type CS_CancelMatch_Ntf struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CS_CancelMatch_Ntf) Reset() {
	*x = CS_CancelMatch_Ntf{}
	mi := &file_protocol_handler_match_handler_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CS_CancelMatch_Ntf) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CS_CancelMatch_Ntf) ProtoMessage() {}

func (x *CS_CancelMatch_Ntf) ProtoReflect() protoreflect.Message {
	mi := &file_protocol_handler_match_handler_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CS_CancelMatch_Ntf.ProtoReflect.Descriptor instead.
func (*CS_CancelMatch_Ntf) Descriptor() ([]byte, []int) {
	return file_protocol_handler_match_handler_proto_rawDescGZIP(), []int{2}
}

var File_protocol_handler_match_handler_proto protoreflect.FileDescriptor

const file_protocol_handler_match_handler_proto_rawDesc = "" +
	"\n" +
	"$protocol/handler/match_handler.proto\x12\x10protocol.handler\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1dprotocol/common/options.proto\"\x1a\n" +
	"\x11CS_StartMatch_Req:\x05\x98\xb5\x18\x98\x11\"\x1a\n" +
	"\x11SC_StartMatch_Rsp:\x05\x98\xb5\x18\x99\x11\"\x1b\n" +
	"\x12CS_CancelMatch_Ntf:\x05\x98\xb5\x18\x9a\x112\xbd\x01\n" +
	"\fMatchHandler\x12V\n" +
	"\n" +
	"StartMatch\x12#.protocol.handler.CS_StartMatch_Req\x1a#.protocol.handler.SC_StartMatch_Rsp\x12K\n" +
	"\vCancelMatch\x12$.protocol.handler.CS_CancelMatch_Ntf\x1a\x16.google.protobuf.Empty\x1a\b\x88\xb5\x18\x00\x90\xb5\x18\x04B$Z\"project/protocol/handler;handlerpbb\x06proto3"

var (
	file_protocol_handler_match_handler_proto_rawDescOnce sync.Once
	file_protocol_handler_match_handler_proto_rawDescData []byte
)

func file_protocol_handler_match_handler_proto_rawDescGZIP() []byte {
	file_protocol_handler_match_handler_proto_rawDescOnce.Do(func() {
		file_protocol_handler_match_handler_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_protocol_handler_match_handler_proto_rawDesc), len(file_protocol_handler_match_handler_proto_rawDesc)))
	})
	return file_protocol_handler_match_handler_proto_rawDescData
}

var file_protocol_handler_match_handler_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_protocol_handler_match_handler_proto_goTypes = []any{
	(*CS_StartMatch_Req)(nil),  // 0: protocol.handler.CS_StartMatch_Req
	(*SC_StartMatch_Rsp)(nil),  // 1: protocol.handler.SC_StartMatch_Rsp
	(*CS_CancelMatch_Ntf)(nil), // 2: protocol.handler.CS_CancelMatch_Ntf
	(*emptypb.Empty)(nil),      // 3: google.protobuf.Empty
}
var file_protocol_handler_match_handler_proto_depIdxs = []int32{
	0, // 0: protocol.handler.MatchHandler.StartMatch:input_type -> protocol.handler.CS_StartMatch_Req
	2, // 1: protocol.handler.MatchHandler.CancelMatch:input_type -> protocol.handler.CS_CancelMatch_Ntf
	1, // 2: protocol.handler.MatchHandler.StartMatch:output_type -> protocol.handler.SC_StartMatch_Rsp
	3, // 3: protocol.handler.MatchHandler.CancelMatch:output_type -> google.protobuf.Empty
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_protocol_handler_match_handler_proto_init() }
func file_protocol_handler_match_handler_proto_init() {
	if File_protocol_handler_match_handler_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_protocol_handler_match_handler_proto_rawDesc), len(file_protocol_handler_match_handler_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_protocol_handler_match_handler_proto_goTypes,
		DependencyIndexes: file_protocol_handler_match_handler_proto_depIdxs,
		MessageInfos:      file_protocol_handler_match_handler_proto_msgTypes,
	}.Build()
	File_protocol_handler_match_handler_proto = out.File
	file_protocol_handler_match_handler_proto_goTypes = nil
	file_protocol_handler_match_handler_proto_depIdxs = nil
}
