// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.3
// source: protocol/service/online_service.proto

package servicepb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	_ "project/protocol/common"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RPC_QueryOnline_Req struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RPC_QueryOnline_Req) Reset() {
	*x = RPC_QueryOnline_Req{}
	mi := &file_protocol_service_online_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RPC_QueryOnline_Req) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RPC_QueryOnline_Req) ProtoMessage() {}

func (x *RPC_QueryOnline_Req) ProtoReflect() protoreflect.Message {
	mi := &file_protocol_service_online_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RPC_QueryOnline_Req.ProtoReflect.Descriptor instead.
func (*RPC_QueryOnline_Req) Descriptor() ([]byte, []int) {
	return file_protocol_service_online_service_proto_rawDescGZIP(), []int{0}
}

type RPC_QueryOnline_Rsp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RPC_QueryOnline_Rsp) Reset() {
	*x = RPC_QueryOnline_Rsp{}
	mi := &file_protocol_service_online_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RPC_QueryOnline_Rsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RPC_QueryOnline_Rsp) ProtoMessage() {}

func (x *RPC_QueryOnline_Rsp) ProtoReflect() protoreflect.Message {
	mi := &file_protocol_service_online_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RPC_QueryOnline_Rsp.ProtoReflect.Descriptor instead.
func (*RPC_QueryOnline_Rsp) Descriptor() ([]byte, []int) {
	return file_protocol_service_online_service_proto_rawDescGZIP(), []int{1}
}

type RPC_Ping_Ntf struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RPC_Ping_Ntf) Reset() {
	*x = RPC_Ping_Ntf{}
	mi := &file_protocol_service_online_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RPC_Ping_Ntf) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RPC_Ping_Ntf) ProtoMessage() {}

func (x *RPC_Ping_Ntf) ProtoReflect() protoreflect.Message {
	mi := &file_protocol_service_online_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RPC_Ping_Ntf.ProtoReflect.Descriptor instead.
func (*RPC_Ping_Ntf) Descriptor() ([]byte, []int) {
	return file_protocol_service_online_service_proto_rawDescGZIP(), []int{2}
}

var File_protocol_service_online_service_proto protoreflect.FileDescriptor

const file_protocol_service_online_service_proto_rawDesc = "" +
	"\n" +
	"%protocol/service/online_service.proto\x12\x10protocol.service\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1dprotocol/common/options.proto\"\x15\n" +
	"\x13RPC_QueryOnline_Req\"\x15\n" +
	"\x13RPC_QueryOnline_Rsp\"\x0e\n" +
	"\fRPC_Ping_Ntf2\xb6\x01\n" +
	"\rOnlineService\x12[\n" +
	"\vQueryOnline\x12%.protocol.service.RPC_QueryOnline_Req\x1a%.protocol.service.RPC_QueryOnline_Rsp\x12>\n" +
	"\x04Ping\x12\x1e.protocol.service.RPC_Ping_Ntf\x1a\x16.google.protobuf.Empty\x1a\b\x88\xb5\x18\x01\x90\xb5\x18\x05B$Z\"project/protocol/service;servicepbb\x06proto3"

var (
	file_protocol_service_online_service_proto_rawDescOnce sync.Once
	file_protocol_service_online_service_proto_rawDescData []byte
)

func file_protocol_service_online_service_proto_rawDescGZIP() []byte {
	file_protocol_service_online_service_proto_rawDescOnce.Do(func() {
		file_protocol_service_online_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_protocol_service_online_service_proto_rawDesc), len(file_protocol_service_online_service_proto_rawDesc)))
	})
	return file_protocol_service_online_service_proto_rawDescData
}

var file_protocol_service_online_service_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_protocol_service_online_service_proto_goTypes = []any{
	(*RPC_QueryOnline_Req)(nil), // 0: protocol.service.RPC_QueryOnline_Req
	(*RPC_QueryOnline_Rsp)(nil), // 1: protocol.service.RPC_QueryOnline_Rsp
	(*RPC_Ping_Ntf)(nil),        // 2: protocol.service.RPC_Ping_Ntf
	(*emptypb.Empty)(nil),       // 3: google.protobuf.Empty
}
var file_protocol_service_online_service_proto_depIdxs = []int32{
	0, // 0: protocol.service.OnlineService.QueryOnline:input_type -> protocol.service.RPC_QueryOnline_Req
	2, // 1: protocol.service.OnlineService.Ping:input_type -> protocol.service.RPC_Ping_Ntf
	1, // 2: protocol.service.OnlineService.QueryOnline:output_type -> protocol.service.RPC_QueryOnline_Rsp
	3, // 3: protocol.service.OnlineService.Ping:output_type -> google.protobuf.Empty
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_protocol_service_online_service_proto_init() }
func file_protocol_service_online_service_proto_init() {
	if File_protocol_service_online_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_protocol_service_online_service_proto_rawDesc), len(file_protocol_service_online_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_protocol_service_online_service_proto_goTypes,
		DependencyIndexes: file_protocol_service_online_service_proto_depIdxs,
		MessageInfos:      file_protocol_service_online_service_proto_msgTypes,
	}.Build()
	File_protocol_service_online_service_proto = out.File
	file_protocol_service_online_service_proto_goTypes = nil
	file_protocol_service_online_service_proto_depIdxs = nil
}
